creatures = {
    "Ceto": {"defeated_by": "", "description": "", "captured_by": None},
    "Tifon": {"defeated_by": "Zeus", "description": "", "captured_by": None},
    "Equidna": {"defeated_by": "Argos Panoptes", "description": "", "captured_by": None},
    "Dino": {"defeated_by": "", "description": "", "captured_by": None},
    "Pefredo": {"defeated_by": "", "description": "", "captured_by": None},
    "Enio": {"defeated_by": "", "description": "", "captured_by": None},
    "Escila": {"defeated_by": "", "description": "", "captured_by": None},
    "Caribdis": {"defeated_by": "", "description": "", "captured_by": None},
    "Euriale": {"defeated_by": "", "description": "", "captured_by": None},
    "Esteno": {"defeated_by": "", "description": "", "captured_by": None},
    "Medusa": {"defeated_by": "Perseo", "description": "", "captured_by": None},
    "Ladon": {"defeated_by": "Heracles", "description": "", "captured_by": None},
    "Aguila del Caucaso": {"defeated_by": "", "description": "", "captured_by": None},
    "Quimera": {"defeated_by": "Belerofonte", "description": "", "captured_by": None},
    "Hidra de Lerna": {"defeated_by": "Heracles", "description": "", "captured_by": None},
    "Leon de Nemea": {"defeated_by": "Heracles", "description": "", "captured_by": None},
    "Esfinge": {"defeated_by": "Edipo", "description": "", "captured_by": None},
    "Dragon de Colquida": {"defeated_by": "", "description": "", "captured_by": None},
    "Cerbero": {"defeated_by": "", "description": "", "captured_by": None},
    "Cerda de Cromion": {"defeated_by": "Teseo", "description": "", "captured_by": None},
    "Ortro": {"defeated_by": "Heracles", "description": "", "captured_by": None},
    "Toro de Creta": {"defeated_by": "Teseo", "description": "", "captured_by": None},
    "Jabali de Calidon": {"defeated_by": "Atalanta", "description": "", "captured_by": None},
    "Carcinos": {"defeated_by": "", "description": "", "captured_by": None},
    "Gerion": {"defeated_by": "Heracles", "description": "", "captured_by": None},
    "Cloto": {"defeated_by": "", "description": "", "captured_by": None},
    "Laquesis": {"defeated_by": "", "description": "", "captured_by": None},
    "Atropos": {"defeated_by": "", "description": "", "captured_by": None},
    "Minotauro de Creta": {"defeated_by": "Teseo", "description": "", "captured_by": None},
    "Harpias": {"defeated_by": "", "description": "", "captured_by": None},
    "Argos Panoptes": {"defeated_by": "Hermes", "description": "", "captured_by": None},
    "Aves del Estinfalo": {"defeated_by": "", "description": "", "captured_by": None},
    "Talos": {"defeated_by": "Medea", "description": "", "captured_by": None},
    "Sirenas": {"defeated_by": "", "description": "", "captured_by": None},
    "Piton": {"defeated_by": "Apolo", "description": "", "captured_by": None},
    "Cierva de Cerinea": {"defeated_by": "", "description": "", "captured_by": None},
    "Basilisco": {"defeated_by": "", "description": "", "captured_by": None},
    "Jabali de Erimanto": {"defeated_by": "", "description": "", "captured_by": None},
}